server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/netmall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "000000"
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        # 自定义静态资源访问路径
        - file:D:/localfile/photos/

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zfx.bsshop.dao
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

logging:
  level:
    com.zfx.bsshop.dao: debug
