server:
  port: 9000
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  servlet:
    multipart:
      enabled: true
      max-request-size: 5GB  # 上传文件总的最大值 默认10MB
      max-file-size: 1GB #单个文件最大值 默认10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/netmall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        # 自定义静态资源访问路径
        - file:D:/localfile/photos/
        - file:D:/project-resources/

# http://localhost:9000/static/show/details/1.1.jpg
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.z
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

logging:
  level:
    com.z.mapper: debug

